In [1]:
import numpy as np
import pandas as pd

In [3]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [4]:
df=pd.read_csv('covid_toy.csv')

In [5]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [6]:
df.shape

(100, 6)

In [7]:
df['cough'].value_counts()

Mild      62
Strong    38
Name: cough, dtype: int64

In [8]:
df['city'].value_counts()

Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: city, dtype: int64

In [9]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test=train_test_split(df.drop(columns=['has_covid']), df['has_covid'],test_size=0.2)

In [11]:
X_train

age  gender  fever   cough       city
15   70    Male  103.0  Strong    Kolkata
73   34    Male   98.0  Strong    Kolkata
2    42    Male  101.0    Mild      Delhi
47   18  Female  104.0    Mild  Bangalore
49   44    Male  104.0    Mild     Mumbai
..  ...     ...    ...     ...        ...
75    5    Male  102.0    Mild    Kolkata
29   34  Female    NaN  Strong     Mumbai
59    6  Female  104.0    Mild    Kolkata
19   42  Female    NaN  Strong  Bangalore
25   23    Male    NaN    Mild     Mumbai

[80 rows x 5 columns]

In [12]:
#adding simple imputer to fever column to fill the null values
si=SimpleImputer()
X_train_fever=si.fit_transform(X_train[['fever']])

#also the test data
X_test_fever=si.fit_transform(X_test[['fever']])

X_train_fever

array([[103.        ],
       [ 98.        ],
       [101.        ],
       [104.        ],
       [104.        ],
       [102.        ],
       [ 98.        ],
       [104.        ],
       [ 98.        ],
       [ 98.        ],
       [101.        ],
       [101.        ],
       [ 99.        ],
       [ 98.        ],
       [101.        ],
       [100.        ],
       [104.        ],
       [100.        ],
       [102.        ],
       [102.        ],
       [104.        ],
       [103.        ],
       [ 99.        ],
       [102.        ],
       [ 98.        ],
       [ 99.        ],
       [100.        ],
       [100.        ],
       [101.        ],
       [100.        ],
       [102.        ],
       [ 98.        ],
       [101.        ],
       [ 98.        ],
       [101.        ],
       [100.        ],
       [ 98.        ],
       [ 98.        ],
       [103.        ],
       [104.        ],
       [102.        ],
       [103.        ],
       [100.71232877],
       [101

In [13]:
#ordinalencoding -> cough
oe=OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough=oe.fit_transform(X_train[['cough']])

#also the test data
X_test_cough=oe.fit_transform(X_test[['cough']])

In [16]:
X_train_cough

array([[1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],

In [17]:
#oneHotencoding for gender&city column
ohe=OneHotEncoder(drop='first', sparse=False)
X_train_gender_city=ohe.fit_transform(X_train[['gender','city']])

# also the test data
X_test_gender_city= ohe.fit_transform(X_test[['gender','city']])

X_train_gender_city

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],


In [18]:
#Extracting Age
X_train_age=X_train.drop(columns=['gender','fever','cough','city']).values

#also the test data
X_test_age=X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age

array([[70],
       [34],
       [42],
       [18],
       [44],
       [82],
       [69],
       [51],
       [40],
       [65],
       [19],
       [51],
       [66],
       [71],
       [ 8],
       [11],
       [51],
       [47],
       [74],
       [64],
       [56],
       [48],
       [22],
       [20],
       [12],
       [49],
       [55],
       [10],
       [38],
       [80],
       [33],
       [24],
       [19],
       [83],
       [65],
       [19],
       [73],
       [80],
       [73],
       [54],
       [82],
       [16],
       [82],
       [34],
       [72],
       [46],
       [23],
       [71],
       [27],
       [60],
       [11],
       [14],
       [83],
       [50],
       [64],
       [79],
       [13],
       [59],
       [20],
       [19],
       [25],
       [64],
       [47],
       [26],
       [24],
       [16],
       [14],
       [10],
       [84],
       [81],
       [69],
       [68],
       [42],
       [81],
       [83],
       [ 5],
       [34],

In [19]:
X_train_transformed=np.concatenate((X_train_age,X_train_fever, X_train_gender_city, X_train_cough),axis=1)

In [20]:
X_test_transformed=np.concatenate((X_test_age, X_test_fever, X_test_gender_city, X_test_cough),axis=1)

In [21]:
X_train_transformed.shape

(80, 7)


We are applying various encoding techniques to a given dataset, and it is computationally intensive when these techniques are applied to each column individually. To address this issue, we are utilizing the ColumnTransformer from scikit-learn. This allows us to efficiently process multiple columns in the dataset, reducing the computational time required.



In [24]:
#ColumnTransformer
from sklearn.compose import ColumnTransformer
transformer=ColumnTransformer(transformers=[

   ('tnf1',SimpleImputer(),['fever']),
   ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
   ('tnf3',OneHotEncoder(sparse=False, drop='first'),['gender','city'])
],remainder='passthrough')

In [25]:
transformer.fit_transform(X_train).shape

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


(80, 7)

In [26]:
transformer.transform(X_test).shape

(20, 7)