# Encoding

In [16]:
import numpy as np
import pandas as pd

In [17]:
df=pd.read_csv("C:/Users/Damodhara/Desktop/Desktop/MACHINE LEARNING/100-days-of-machine-learning-main/day26-ordinal-encoding/customer.csv")

In [18]:
df.sample(5)

age  gender   review education purchased
26   53  Female     Poor        PG        No
11   74    Male     Good        UG       Yes
10   98  Female     Good        UG       Yes
0    30  Female  Average    School        No
32   92    Male  Average        UG       Yes

In [19]:
df=df.iloc[:,2:]

In [20]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [21]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1], test_size=0.2)

In [22]:
X_train

review education
21  Average        PG
45     Poor        PG
12     Poor    School
13  Average    School
27     Poor        PG
29  Average        UG
1      Poor        UG
47     Good        PG
26     Poor        PG
31     Poor    School
39     Poor        PG
28     Poor    School
25     Good    School
48     Good        UG
4   Average        UG
16     Poor        UG
49     Good        UG
18     Good    School
24  Average        PG
6      Good    School
33     Good        PG
43     Poor        PG
23     Good    School
41     Good        PG
34  Average    School
10     Good        UG
3      Good        PG
19     Poor        PG
30  Average        UG
15     Poor        UG
9      Good        UG
36     Good        UG
7      Poor    School
8   Average        UG
42     Good        PG
5   Average    School
22     Poor        PG
11     Good        UG
20  Average    School
35     Poor    School

#### Ordinal Encoding 

In [44]:
# ordinal encoding for review, education columns 

In [25]:
from sklearn.preprocessing import OrdinalEncoder

In [26]:
oe = OrdinalEncoder(categories=[["Poor","Average","Good"],["School","UG","PG"]])

In [27]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [28]:
X_train=oe.transform(X_train)
X_test=oe.transform(X_test)

In [29]:
X_train

array([[1., 2.],
       [0., 2.],
       [0., 0.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [0., 1.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [0., 2.],
       [0., 0.],
       [2., 0.],
       [2., 1.],
       [1., 1.],
       [0., 1.],
       [2., 1.],
       [2., 0.],
       [1., 2.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [2., 0.],
       [2., 2.],
       [1., 0.],
       [2., 1.],
       [2., 2.],
       [0., 2.],
       [1., 1.],
       [0., 1.],
       [2., 1.],
       [2., 1.],
       [0., 0.],
       [1., 1.],
       [2., 2.],
       [1., 0.],
       [0., 2.],
       [2., 1.],
       [1., 0.],
       [0., 0.]])

In [31]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [32]:
X_train

array([[1., 2.],
       [0., 2.],
       [0., 0.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [0., 1.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [0., 2.],
       [0., 0.],
       [2., 0.],
       [2., 1.],
       [1., 1.],
       [0., 1.],
       [2., 1.],
       [2., 0.],
       [1., 2.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [2., 0.],
       [2., 2.],
       [1., 0.],
       [2., 1.],
       [2., 2.],
       [0., 2.],
       [1., 1.],
       [0., 1.],
       [2., 1.],
       [2., 1.],
       [0., 0.],
       [1., 1.],
       [2., 2.],
       [1., 0.],
       [0., 2.],
       [2., 1.],
       [1., 0.],
       [0., 0.]])

#### Label Encoding 


In [43]:
# Label encoding for purchased column 

In [35]:
from sklearn.preprocessing import LabelEncoder

In [36]:
le=LabelEncoder()

In [37]:
le.fit(y_train)

LabelEncoder()

In [38]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [39]:
y_train=le.transform(y_train)
y_test=le.transform(y_test)

In [40]:
y_train

array([0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1])

#### OneHotEncoding

In [42]:
df1=pd.read_csv("C:/Users/Damodhara/Desktop/Desktop/MACHINE LEARNING/100-days-of-machine-learning-main/day27-one-hot-encoding/cars.csv")

In [45]:
df1.head()

brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [47]:
df1["brand"].value_counts()

Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: brand, dtype: int64

In [48]:
df1["brand"].nunique()

32

In [49]:
df1["fuel"].value_counts()

Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: fuel, dtype: int64

In [50]:
df1["owner"].value_counts()

First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: owner, dtype: int64

#### 1.OneHotEncoding using Pandas

In [53]:
pd.get_dummies(df1,columns=["fuel","owner"])

brand  km_driven  selling_price  fuel_CNG  fuel_Diesel  fuel_LPG  \
0      Maruti     145500         450000         0            1         0   
1       Skoda     120000         370000         0            1         0   
2       Honda     140000         158000         0            0         0   
3     Hyundai     127000         225000         0            1         0   
4      Maruti     120000         130000         0            0         0   
...       ...        ...            ...       ...          ...       ...   
8123  Hyundai     110000         320000         0            0         0   
8124  Hyundai     119000         135000         0            1         0   
8125   Maruti     120000         382000         0            1         0   
8126     Tata      25000         290000         0            1         0   
8127     Tata      25000         290000         0            1         0   

      fuel_Petrol  owner_First Owner  owner_Fourth & Above Owner  \
0               0                  1                           0   
1               0                  0                           0   
2               1                  0                           0   
3               0                  1                           0   
4               1                  1                           0   
...           ...                ...                         ...   
8123            1                  1                           0   
8124            0                  0                           1   
8125            0                  1                           0   
8126            0                  1                           0   
8127            0                  1                           0   

      owner_Second Owner  owner_Test Drive Car  owner_Third Owner  
0                      0                     0                  0  
1                      1                     0                  0  
2                      0                     0                  1  
3                      0                     0                  0  
4                      0                     0                  0  
...                  ...                   ...                ...  
8123                   0                     0                  0  
8124                   0                     0                  0  
8125                   0                     0                  0  
8126                   0                     0                  0  
8127                   0                     0                  0  

[8128 rows x 12 columns]

#### 2.k-1 OneHotEncoding

In [56]:
pd.get_dummies(df1,columns=["fuel","owner"],drop_first='first')

brand  km_driven  selling_price  fuel_Diesel  fuel_LPG  fuel_Petrol  \
0      Maruti     145500         450000            1         0            0   
1       Skoda     120000         370000            1         0            0   
2       Honda     140000         158000            0         0            1   
3     Hyundai     127000         225000            1         0            0   
4      Maruti     120000         130000            0         0            1   
...       ...        ...            ...          ...       ...          ...   
8123  Hyundai     110000         320000            0         0            1   
8124  Hyundai     119000         135000            1         0            0   
8125   Maruti     120000         382000            1         0            0   
8126     Tata      25000         290000            1         0            0   
8127     Tata      25000         290000            1         0            0   

      owner_Fourth & Above Owner  owner_Second Owner  owner_Test Drive Car  \
0                              0                   0                     0   
1                              0                   1                     0   
2                              0                   0                     0   
3                              0                   0                     0   
4                              0                   0                     0   
...                          ...                 ...                   ...   
8123                           0                   0                     0   
8124                           1                   0                     0   
8125                           0                   0                     0   
8126                           0                   0                     0   
8127                           0                   0                     0   

      owner_Third Owner  
0                     0  
1                     0  
2                     1  
3                     0  
4                     0  
...                 ...  
8123                  0  
8124                  0  
8125                  0  
8126                  0  
8127                  0  

[8128 rows x 10 columns]

#### 3. OneHotEncoding using Sklearn

In [57]:
from sklearn.model_selection import train_test_split

In [59]:
X_train,X_test,y_train,y_test = train_test_split(df1.iloc[:,0:4],df1.iloc[:,-1],test_size=0.2,random_state=2)

In [60]:
X_train.head()

brand  km_driven    fuel         owner
5571   Hyundai      35000  Diesel   First Owner
2038      Jeep      60000  Diesel   First Owner
2957   Hyundai      25000  Petrol   First Owner
7618  Mahindra     130000  Diesel  Second Owner
6684   Hyundai     155000  Diesel   First Owner

In [61]:
from sklearn.preprocessing import OneHotEncoder

In [62]:
ohe=OneHotEncoder(drop="first",sparse=False,dtype=np.int32)

In [65]:
ohe

OneHotEncoder(drop='first', dtype=<class 'numpy.int32'>, sparse=False)

In [63]:
X_train_new=ohe.fit_transform(X_train[["fuel","owner"]])

In [64]:
X_train_new

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]])

In [66]:
X_train_new.shape

(6502, 7)

In [67]:
np.hstack((X_train[["brand","km_driven"]].values,X_train_new))

array([['Hyundai', 35000, 1, ..., 0, 0, 0],
       ['Jeep', 60000, 1, ..., 0, 0, 0],
       ['Hyundai', 25000, 0, ..., 0, 0, 0],
       ...,
       ['Tata', 15000, 0, ..., 0, 0, 0],
       ['Maruti', 32500, 1, ..., 1, 0, 0],
       ['Isuzu', 121000, 1, ..., 0, 0, 0]], dtype=object)

#### 4.OneHotEncoding with Top Categories

In [69]:
counts = df1["brand"].value_counts()

In [71]:
df1["brand"].unique()
threshold=100

In [72]:
rep1=counts[counts<=threshold].index

In [74]:
pd.get_dummies(df1['brand'].replace(rep1, 'uncommon')).sample(5)


BMW  Chevrolet  Ford  Honda  Hyundai  Mahindra  Maruti  Renault  Skoda  \
1047    0          0     0      0        0         0       0        1      0   
6280    0          0     0      0        0         0       1        0      0   
944     0          0     0      0        1         0       0        0      0   
1091    1          0     0      0        0         0       0        0      0   
4445    0          0     0      0        0         0       1        0      0   

      Tata  Toyota  Volkswagen  uncommon  
1047     0       0           0         0  
6280     0       0           0         0  
944      0       0           0         0  
1091     0       0           0         0  
4445     0       0           0         0